export const CATEGORIES = [
  { id: 1, name: 'Tecnología' },
  { id: 2, name: 'Hogar' },
  { id: 3, name: 'Muebles' },
  { id: 4, name: 'Electrodomésticos' },
  { id: 5, name: 'Alimentos' },
  { id: 6, name: 'Herramientas' },
  { id: 7, name: 'Ropa' },
  { id: 8, name: 'Documentos' },
  { id: 9, name: 'Farmacéutico' },
  { id: 10, name: 'Belleza' },
  { id: 11, name: 'Deportes' },
  { id: 12, name: 'Accesorios' },
  { id: 13, name: 'Construcción' },
  { id: 14, name: 'Químicos' },
  { id: 15, name: 'Juguetería' },
  { id: 16, name: 'Automotriz' },
  { id: 17, name: 'Mascotas' },
  { id: 18, name: 'Librería' },
  { id: 19, name: 'Electrónica' },
  { id: 20, name: 'Otros' },
];
