import type { Metadata } from 'next';
// import de fuentes inter y poppins de google
import { Inter, Poppins } from 'next/font/google';
// import next-intl para idiomas
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import '../globals.css';
import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import FloatingActions from '@/components/FloatingActions';

// fuente poppins e inter
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-poppins',
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const messages = await getMessages();

  return (
    <html lang={locale} className={`${poppins.variable} ${inter.variable}`}>
      <body className="min-h-screen flex flex-col bg-background text-foreground">
        <NextIntlClientProvider messages={messages}>
          <Navbar />
          <main className="flex-1">{children}</main>
          <FloatingActions />
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
